# Generated by Django 4.0.6 on 2023-12-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideImg', models.ImageField(upload_to='gallery/')),
            ],
        ),
    ]
