# Generated by Django 4.0.6 on 2023-12-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsImage', models.ImageField(upload_to='news/')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=60)),
                ('date', models.CharField(max_length=20)),
                ('info', models.TextField()),
            ],
        ),
    ]
