# Generated by Django 4.0.6 on 2023-12-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='postDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
