# Generated by Django 4.0.6 on 2023-12-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_news_postdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffImage', models.ImageField(upload_to='staff/')),
                ('name', models.CharField(max_length=45)),
                ('position', models.CharField(max_length=45)),
            ],
        ),
    ]
